services:
  prod_postgres:
    image: postgres
    env_file:
      - ./.env.prod
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    networks:
      - prod-network

  prod_server:
    container_name: prod_server
    build:
      context: .
      dockerfile: ./server.local.dockerfile
    ports:
      - 8000:80
    env_file:
      - ./.env.prod
    depends_on:
      prod_postgres:
        condition: service_healthy
    networks:
      - prod-network

networks:
  prod-network:
    driver: bridge

volumes:
  pg_data:
