services:
  local_migrate:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    extra_hosts:
      - "host.docker.internal:host-gateway"

  local_sqlc:
    image: sqlc/sqlc
    command: generate
    volumes:
      - ./:/app
    working_dir: /app

  local_postgres:
    image: postgres
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data

  local_server:
    container_name: local_server
    build:
      context: .
      dockerfile: ./docker/server/local.dockerfile
    ports:
      - 8000:80
    env_file:
      - ./.env.local
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      local_postgres:
        condition: service_healthy
    volumes:
      - ./:/app
