// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MobileOtp struct {
	ID        int32            `json:"id"`
	UserID    int32            `json:"user_id"`
	Otp       string           `json:"otp"`
	ValidTill pgtype.Timestamp `json:"valid_till"`
	IsUsed    pgtype.Bool      `json:"is_used"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID            int32       `json:"id"`
	Username      string      `json:"username"`
	MobileNumber  int32       `json:"mobile_number"`
	Password      string      `json:"password"`
	PrimaryDevice string      `json:"primary_device"`
	Sex           pgtype.Text `json:"sex"`
	Age           pgtype.Int4 `json:"age"`
	IsDeleted     pgtype.Bool `json:"is_deleted"`
}
