// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres_db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID            int32       `json:"id"`
	Username      string      `json:"username"`
	Password      string      `json:"password"`
	PrimaryDevice string      `json:"primary_device"`
	Sex           pgtype.Text `json:"sex"`
	Age           pgtype.Int4 `json:"age"`
	IsDeleted     pgtype.Bool `json:"is_deleted"`
}
