basePath: /
definitions:
  auth.LoginRequest:
    properties:
      password:
        type: string
      user_name:
        type: string
    required:
    - password
    - user_name
    type: object
  auth.LoginResponse:
    properties:
      access_token:
        type: string
      is_new_device:
        type: boolean
      new_device_id:
        type: string
      old_device_id:
        type: string
    type: object
  auth.OtpRequest:
    properties:
      user_name:
        type: string
    required:
    - user_name
    type: object
  auth.SignUpRequest:
    properties:
      age:
        type: integer
      password:
        type: string
      sex:
        type: string
      user_name:
        type: string
    type: object
  auth.SignUpResponse:
    properties:
      msg:
        type: string
    type: object
  health.HealthResponse:
    properties:
      device_id:
        description: Server time in Unix timestamp (seconds)
        type: string
      msg:
        description: Message
        type: string
      server_time:
        description: Server time in Unix timestamp (seconds)
        type: integer
    type: object
  response.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  response.SuccessResponse:
    properties:
      data: {}
      msg:
        type: string
    type: object
  user.User:
    properties:
      age:
        type: integer
      id:
        type: integer
      primary_device:
        type: string
      sex:
        type: string
      username:
        type: string
    type: object
  user.UserResponse:
    properties:
      msg:
        type: string
      user_data:
        $ref: '#/definitions/user.User'
    type: object
host: localhost:8000
info:
  contact:
    name: github.com/tetrex
  description: This is a backend api server
  license:
    name: MIT License
  title: server api
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: returns server time
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/health.HealthResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Get Health check status
      tags:
      - Health
  /v1/generate-otp:
    post:
      consumes:
      - application/json
      description: Sends Otp To User
      parameters:
      - description: OtpRequest
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.OtpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SuccessResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Send Otp
      tags:
      - Auth
  /v1/get-valid-otp:
    post:
      consumes:
      - application/json
      description: Sends Otp To User
      parameters:
      - description: OtpRequest
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.OtpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SuccessResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Send Otp
      tags:
      - Auth
  /v1/login:
    post:
      consumes:
      - application/json
      description: Login for User
      parameters:
      - description: LoginRequest
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: User Login
      tags:
      - Auth
  /v1/signup:
    post:
      consumes:
      - application/json
      description: Creates New User Account
      parameters:
      - description: SignUpRequest
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.SignUpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: User Signup
      tags:
      - Auth
  /v1/user:
    get:
      consumes:
      - application/json
      description: Get User detail by id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: User Deatils
      tags:
      - User
swagger: "2.0"
